name = "zkLean"
version = "0.1.0"
defaultTargets = ["zklean"]

[[lean_lib]]
name = "ZkLean"

[[lean_exe]]
name = "zklean"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.21.0"

[[require]]
name = "mpl"
git = "https://github.com/sgraf812/mpl"
rev = "52e8300"

[[require]]
name = "bvmod_eq"
path = "../bvmod_eq/src"